# Generated by Django 6.0.3 on 2026-04-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='dashboard.company')),
            ],
            options={
                'ordering': ['subject'],
                'unique_together': {('company', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_titles', to='dashboard.testsubject')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('test_subject', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=20)),
                ('questions_json', models.JSONField(default=list, help_text='Bulk-uploaded question bank as a JSON array.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='dashboard.subtitle')),
                ('test_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='dashboard.testsubject')),
            ],
            options={
                'ordering': ['test_subject__subject', 'sub_title__title', 'level'],
            },
        ),
    ]
