# Generated by Django 6.0.3 on 2026-04-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions_json',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3'), ('option_4', 'Option 4')], default='option_1', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BulkQuestionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=20)),
                ('json_file', models.FileField(blank=True, null=True, upload_to='bulk_questions/')),
                ('questions_json', models.JSONField(blank=True, default=list, help_text='Optional pasted JSON array. Use this only for bulk import data.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='dashboard.subtitle')),
                ('test_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='dashboard.testsubject')),
            ],
            options={
                'verbose_name': 'Bulk Question Upload',
                'verbose_name_plural': 'Bulk Question Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
