# Generated by Django 6.0.3 on 2026-04-17 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_quiz_questions_json_quiz_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkquestionupload',
            name='imported_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkquestionupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='bulk_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_quizzes', to='dashboard.bulkquestionupload'),
        ),
    ]
