# Generated by Django 6.0.3 on 2026-04-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bulkquestionupload_imported_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkquestionupload',
            name='sub_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads', to='dashboard.subtitle'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='sub_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='dashboard.subtitle'),
        ),
    ]
