# Generated by Django 6.0.3 on 2026-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_bulkquestionupload_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubject',
            name='subject_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
