# Generated by Django 6.0.3 on 2026-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_testsubject_subject_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='exam_control_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='full_screen_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='pause_lock',
            field=models.BooleanField(default=False),
        ),
    ]
