# Generated by Django 6.0.3 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_company_exam_control_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_violation_warnings',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='company',
            name='tab_switch_guard_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
