# Generated by Django 6.0.3 on 2026-07-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_company_mail_sender_enabled_company_smtp_app_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pass_persantage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
    ]
