# Generated by Django 5.0.6 on 2026-07-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_company_pass_persantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_multi_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='multi_user_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
