# Generated by Django 6.0.3 on 2026-04-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('designation_tech', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('single', 'Single'), ('multi', 'Multi')], max_length=10)),
                ('level', models.CharField(max_length=20)),
                ('question_count', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('selected_subjects', models.JSONField(blank=True, default=list)),
                ('selected_sub_titles', models.JSONField(blank=True, default=list)),
                ('answers_json', models.JSONField(blank=True, default=list)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dashboard.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
