# Generated by Django 6.0.3 on 2026-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestattempt',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
