# Generated by Django 6.0.3 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_candidatetestattempt_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestattempt',
            name='last_violation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='violation_log_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
