# Generated by Django 6.0.4 on 2026-06-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_candidatetestattempt_candidate_details_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestattempt',
            name='test_link_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
