# Generated by Django 5.0.6 on 2026-07-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestattempt',
            name='active_session_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='multi_user_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
